// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dns.proto

package main

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DnsHeaderFlags struct {
	AuthoritativeAnswer  bool     `protobuf:"varint,1,opt,name=authoritative_answer,json=authoritativeAnswer,proto3" json:"authoritative_answer,omitempty"`
	TruncatedResponse    bool     `protobuf:"varint,2,opt,name=truncated_response,json=truncatedResponse,proto3" json:"truncated_response,omitempty"`
	RecursionDesired     bool     `protobuf:"varint,3,opt,name=recursion_desired,json=recursionDesired,proto3" json:"recursion_desired,omitempty"`
	RecursionAvailable   bool     `protobuf:"varint,4,opt,name=recursion_available,json=recursionAvailable,proto3" json:"recursion_available,omitempty"`
	Z                    uint32   `protobuf:"varint,5,opt,name=z,proto3" json:"z,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DnsHeaderFlags) Reset()         { *m = DnsHeaderFlags{} }
func (m *DnsHeaderFlags) String() string { return proto.CompactTextString(m) }
func (*DnsHeaderFlags) ProtoMessage()    {}
func (*DnsHeaderFlags) Descriptor() ([]byte, []int) {
	return fileDescriptor_638ff8d8aaf3d8ae, []int{0}
}

func (m *DnsHeaderFlags) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DnsHeaderFlags.Unmarshal(m, b)
}
func (m *DnsHeaderFlags) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DnsHeaderFlags.Marshal(b, m, deterministic)
}
func (m *DnsHeaderFlags) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DnsHeaderFlags.Merge(m, src)
}
func (m *DnsHeaderFlags) XXX_Size() int {
	return xxx_messageInfo_DnsHeaderFlags.Size(m)
}
func (m *DnsHeaderFlags) XXX_DiscardUnknown() {
	xxx_messageInfo_DnsHeaderFlags.DiscardUnknown(m)
}

var xxx_messageInfo_DnsHeaderFlags proto.InternalMessageInfo

func (m *DnsHeaderFlags) GetAuthoritativeAnswer() bool {
	if m != nil {
		return m.AuthoritativeAnswer
	}
	return false
}

func (m *DnsHeaderFlags) GetTruncatedResponse() bool {
	if m != nil {
		return m.TruncatedResponse
	}
	return false
}

func (m *DnsHeaderFlags) GetRecursionDesired() bool {
	if m != nil {
		return m.RecursionDesired
	}
	return false
}

func (m *DnsHeaderFlags) GetRecursionAvailable() bool {
	if m != nil {
		return m.RecursionAvailable
	}
	return false
}

func (m *DnsHeaderFlags) GetZ() uint32 {
	if m != nil {
		return m.Z
	}
	return 0
}

type DnsHeader struct {
	DnsTxId              uint32          `protobuf:"varint,1,opt,name=dns_tx_id,json=dnsTxId,proto3" json:"dns_tx_id,omitempty"`
	IsResponse           bool            `protobuf:"varint,2,opt,name=is_response,json=isResponse,proto3" json:"is_response,omitempty"`
	OpCode               uint32          `protobuf:"varint,3,opt,name=op_code,json=opCode,proto3" json:"op_code,omitempty"`
	Flags                *DnsHeaderFlags `protobuf:"bytes,4,opt,name=flags,proto3" json:"flags,omitempty"`
	ResponseCode         uint32          `protobuf:"varint,5,opt,name=response_code,json=responseCode,proto3" json:"response_code,omitempty"`
	QuestionCount        uint32          `protobuf:"varint,6,opt,name=question_count,json=questionCount,proto3" json:"question_count,omitempty"`
	AnswerCount          uint32          `protobuf:"varint,7,opt,name=answer_count,json=answerCount,proto3" json:"answer_count,omitempty"`
	AuthorityCount       uint32          `protobuf:"varint,8,opt,name=authority_count,json=authorityCount,proto3" json:"authority_count,omitempty"`
	AdditionalCount      uint32          `protobuf:"varint,9,opt,name=additional_count,json=additionalCount,proto3" json:"additional_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *DnsHeader) Reset()         { *m = DnsHeader{} }
func (m *DnsHeader) String() string { return proto.CompactTextString(m) }
func (*DnsHeader) ProtoMessage()    {}
func (*DnsHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_638ff8d8aaf3d8ae, []int{1}
}

func (m *DnsHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DnsHeader.Unmarshal(m, b)
}
func (m *DnsHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DnsHeader.Marshal(b, m, deterministic)
}
func (m *DnsHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DnsHeader.Merge(m, src)
}
func (m *DnsHeader) XXX_Size() int {
	return xxx_messageInfo_DnsHeader.Size(m)
}
func (m *DnsHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_DnsHeader.DiscardUnknown(m)
}

var xxx_messageInfo_DnsHeader proto.InternalMessageInfo

func (m *DnsHeader) GetDnsTxId() uint32 {
	if m != nil {
		return m.DnsTxId
	}
	return 0
}

func (m *DnsHeader) GetIsResponse() bool {
	if m != nil {
		return m.IsResponse
	}
	return false
}

func (m *DnsHeader) GetOpCode() uint32 {
	if m != nil {
		return m.OpCode
	}
	return 0
}

func (m *DnsHeader) GetFlags() *DnsHeaderFlags {
	if m != nil {
		return m.Flags
	}
	return nil
}

func (m *DnsHeader) GetResponseCode() uint32 {
	if m != nil {
		return m.ResponseCode
	}
	return 0
}

func (m *DnsHeader) GetQuestionCount() uint32 {
	if m != nil {
		return m.QuestionCount
	}
	return 0
}

func (m *DnsHeader) GetAnswerCount() uint32 {
	if m != nil {
		return m.AnswerCount
	}
	return 0
}

func (m *DnsHeader) GetAuthorityCount() uint32 {
	if m != nil {
		return m.AuthorityCount
	}
	return 0
}

func (m *DnsHeader) GetAdditionalCount() uint32 {
	if m != nil {
		return m.AdditionalCount
	}
	return 0
}

type Question struct {
	Name                 []byte   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Class                string   `protobuf:"bytes,3,opt,name=class,proto3" json:"class,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Question) Reset()         { *m = Question{} }
func (m *Question) String() string { return proto.CompactTextString(m) }
func (*Question) ProtoMessage()    {}
func (*Question) Descriptor() ([]byte, []int) {
	return fileDescriptor_638ff8d8aaf3d8ae, []int{2}
}

func (m *Question) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Question.Unmarshal(m, b)
}
func (m *Question) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Question.Marshal(b, m, deterministic)
}
func (m *Question) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Question.Merge(m, src)
}
func (m *Question) XXX_Size() int {
	return xxx_messageInfo_Question.Size(m)
}
func (m *Question) XXX_DiscardUnknown() {
	xxx_messageInfo_Question.DiscardUnknown(m)
}

var xxx_messageInfo_Question proto.InternalMessageInfo

func (m *Question) GetName() []byte {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *Question) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Question) GetClass() string {
	if m != nil {
		return m.Class
	}
	return ""
}

type ResourceRecord struct {
	Name                 []byte            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type                 string            `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Class                string            `protobuf:"bytes,3,opt,name=class,proto3" json:"class,omitempty"`
	Ttl                  uint32            `protobuf:"varint,4,opt,name=ttl,proto3" json:"ttl,omitempty"`
	StringData           string            `protobuf:"bytes,5,opt,name=string_data,json=stringData,proto3" json:"string_data,omitempty"`
	ByteData             []byte            `protobuf:"bytes,6,opt,name=byte_data,json=byteData,proto3" json:"byte_data,omitempty"`
	Soa                  *StartOfAuthority `protobuf:"bytes,7,opt,name=soa,proto3" json:"soa,omitempty"`
	Mx                   *MailExchange     `protobuf:"bytes,8,opt,name=mx,proto3" json:"mx,omitempty"`
	Srv                  *ServiceRecord    `protobuf:"bytes,9,opt,name=srv,proto3" json:"srv,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ResourceRecord) Reset()         { *m = ResourceRecord{} }
func (m *ResourceRecord) String() string { return proto.CompactTextString(m) }
func (*ResourceRecord) ProtoMessage()    {}
func (*ResourceRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_638ff8d8aaf3d8ae, []int{3}
}

func (m *ResourceRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResourceRecord.Unmarshal(m, b)
}
func (m *ResourceRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResourceRecord.Marshal(b, m, deterministic)
}
func (m *ResourceRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourceRecord.Merge(m, src)
}
func (m *ResourceRecord) XXX_Size() int {
	return xxx_messageInfo_ResourceRecord.Size(m)
}
func (m *ResourceRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourceRecord.DiscardUnknown(m)
}

var xxx_messageInfo_ResourceRecord proto.InternalMessageInfo

func (m *ResourceRecord) GetName() []byte {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *ResourceRecord) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *ResourceRecord) GetClass() string {
	if m != nil {
		return m.Class
	}
	return ""
}

func (m *ResourceRecord) GetTtl() uint32 {
	if m != nil {
		return m.Ttl
	}
	return 0
}

func (m *ResourceRecord) GetStringData() string {
	if m != nil {
		return m.StringData
	}
	return ""
}

func (m *ResourceRecord) GetByteData() []byte {
	if m != nil {
		return m.ByteData
	}
	return nil
}

func (m *ResourceRecord) GetSoa() *StartOfAuthority {
	if m != nil {
		return m.Soa
	}
	return nil
}

func (m *ResourceRecord) GetMx() *MailExchange {
	if m != nil {
		return m.Mx
	}
	return nil
}

func (m *ResourceRecord) GetSrv() *ServiceRecord {
	if m != nil {
		return m.Srv
	}
	return nil
}

type DnsInfo struct {
	Header               *DnsHeader        `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Questions            []*Question       `protobuf:"bytes,2,rep,name=questions,proto3" json:"questions,omitempty"`
	Answers              []*ResourceRecord `protobuf:"bytes,3,rep,name=answers,proto3" json:"answers,omitempty"`
	Authorities          []*ResourceRecord `protobuf:"bytes,4,rep,name=authorities,proto3" json:"authorities,omitempty"`
	Additionals          []*ResourceRecord `protobuf:"bytes,5,rep,name=additionals,proto3" json:"additionals,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DnsInfo) Reset()         { *m = DnsInfo{} }
func (m *DnsInfo) String() string { return proto.CompactTextString(m) }
func (*DnsInfo) ProtoMessage()    {}
func (*DnsInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_638ff8d8aaf3d8ae, []int{4}
}

func (m *DnsInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DnsInfo.Unmarshal(m, b)
}
func (m *DnsInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DnsInfo.Marshal(b, m, deterministic)
}
func (m *DnsInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DnsInfo.Merge(m, src)
}
func (m *DnsInfo) XXX_Size() int {
	return xxx_messageInfo_DnsInfo.Size(m)
}
func (m *DnsInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_DnsInfo.DiscardUnknown(m)
}

var xxx_messageInfo_DnsInfo proto.InternalMessageInfo

func (m *DnsInfo) GetHeader() *DnsHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *DnsInfo) GetQuestions() []*Question {
	if m != nil {
		return m.Questions
	}
	return nil
}

func (m *DnsInfo) GetAnswers() []*ResourceRecord {
	if m != nil {
		return m.Answers
	}
	return nil
}

func (m *DnsInfo) GetAuthorities() []*ResourceRecord {
	if m != nil {
		return m.Authorities
	}
	return nil
}

func (m *DnsInfo) GetAdditionals() []*ResourceRecord {
	if m != nil {
		return m.Additionals
	}
	return nil
}

type DnsPacket struct {
	Timestamp            int64    `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	IsInbound            bool     `protobuf:"varint,2,opt,name=is_inbound,json=isInbound,proto3" json:"is_inbound,omitempty"`
	EthType              uint32   `protobuf:"varint,3,opt,name=eth_type,json=ethType,proto3" json:"eth_type,omitempty"`
	SrcIp                string   `protobuf:"bytes,4,opt,name=src_ip,json=srcIp,proto3" json:"src_ip,omitempty"`
	DstIp                string   `protobuf:"bytes,5,opt,name=dst_ip,json=dstIp,proto3" json:"dst_ip,omitempty"`
	PacketBytes          uint32   `protobuf:"varint,6,opt,name=packet_bytes,json=packetBytes,proto3" json:"packet_bytes,omitempty"`
	DnsInfo              *DnsInfo `protobuf:"bytes,7,opt,name=dns_info,json=dnsInfo,proto3" json:"dns_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DnsPacket) Reset()         { *m = DnsPacket{} }
func (m *DnsPacket) String() string { return proto.CompactTextString(m) }
func (*DnsPacket) ProtoMessage()    {}
func (*DnsPacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_638ff8d8aaf3d8ae, []int{5}
}

func (m *DnsPacket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DnsPacket.Unmarshal(m, b)
}
func (m *DnsPacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DnsPacket.Marshal(b, m, deterministic)
}
func (m *DnsPacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DnsPacket.Merge(m, src)
}
func (m *DnsPacket) XXX_Size() int {
	return xxx_messageInfo_DnsPacket.Size(m)
}
func (m *DnsPacket) XXX_DiscardUnknown() {
	xxx_messageInfo_DnsPacket.DiscardUnknown(m)
}

var xxx_messageInfo_DnsPacket proto.InternalMessageInfo

func (m *DnsPacket) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *DnsPacket) GetIsInbound() bool {
	if m != nil {
		return m.IsInbound
	}
	return false
}

func (m *DnsPacket) GetEthType() uint32 {
	if m != nil {
		return m.EthType
	}
	return 0
}

func (m *DnsPacket) GetSrcIp() string {
	if m != nil {
		return m.SrcIp
	}
	return ""
}

func (m *DnsPacket) GetDstIp() string {
	if m != nil {
		return m.DstIp
	}
	return ""
}

func (m *DnsPacket) GetPacketBytes() uint32 {
	if m != nil {
		return m.PacketBytes
	}
	return 0
}

func (m *DnsPacket) GetDnsInfo() *DnsInfo {
	if m != nil {
		return m.DnsInfo
	}
	return nil
}

type DnsPacketBundle struct {
	Packets              []*DnsPacket `protobuf:"bytes,1,rep,name=packets,proto3" json:"packets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *DnsPacketBundle) Reset()         { *m = DnsPacketBundle{} }
func (m *DnsPacketBundle) String() string { return proto.CompactTextString(m) }
func (*DnsPacketBundle) ProtoMessage()    {}
func (*DnsPacketBundle) Descriptor() ([]byte, []int) {
	return fileDescriptor_638ff8d8aaf3d8ae, []int{6}
}

func (m *DnsPacketBundle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DnsPacketBundle.Unmarshal(m, b)
}
func (m *DnsPacketBundle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DnsPacketBundle.Marshal(b, m, deterministic)
}
func (m *DnsPacketBundle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DnsPacketBundle.Merge(m, src)
}
func (m *DnsPacketBundle) XXX_Size() int {
	return xxx_messageInfo_DnsPacketBundle.Size(m)
}
func (m *DnsPacketBundle) XXX_DiscardUnknown() {
	xxx_messageInfo_DnsPacketBundle.DiscardUnknown(m)
}

var xxx_messageInfo_DnsPacketBundle proto.InternalMessageInfo

func (m *DnsPacketBundle) GetPackets() []*DnsPacket {
	if m != nil {
		return m.Packets
	}
	return nil
}

type StartOfAuthority struct {
	MName                []byte   `protobuf:"bytes,1,opt,name=m_name,json=mName,proto3" json:"m_name,omitempty"`
	RName                []byte   `protobuf:"bytes,2,opt,name=r_name,json=rName,proto3" json:"r_name,omitempty"`
	Serial               uint32   `protobuf:"varint,3,opt,name=serial,proto3" json:"serial,omitempty"`
	Refresh              uint32   `protobuf:"varint,4,opt,name=refresh,proto3" json:"refresh,omitempty"`
	Retry                uint32   `protobuf:"varint,5,opt,name=retry,proto3" json:"retry,omitempty"`
	Expire               uint32   `protobuf:"varint,6,opt,name=expire,proto3" json:"expire,omitempty"`
	Minimum              uint32   `protobuf:"varint,7,opt,name=minimum,proto3" json:"minimum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartOfAuthority) Reset()         { *m = StartOfAuthority{} }
func (m *StartOfAuthority) String() string { return proto.CompactTextString(m) }
func (*StartOfAuthority) ProtoMessage()    {}
func (*StartOfAuthority) Descriptor() ([]byte, []int) {
	return fileDescriptor_638ff8d8aaf3d8ae, []int{7}
}

func (m *StartOfAuthority) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartOfAuthority.Unmarshal(m, b)
}
func (m *StartOfAuthority) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartOfAuthority.Marshal(b, m, deterministic)
}
func (m *StartOfAuthority) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartOfAuthority.Merge(m, src)
}
func (m *StartOfAuthority) XXX_Size() int {
	return xxx_messageInfo_StartOfAuthority.Size(m)
}
func (m *StartOfAuthority) XXX_DiscardUnknown() {
	xxx_messageInfo_StartOfAuthority.DiscardUnknown(m)
}

var xxx_messageInfo_StartOfAuthority proto.InternalMessageInfo

func (m *StartOfAuthority) GetMName() []byte {
	if m != nil {
		return m.MName
	}
	return nil
}

func (m *StartOfAuthority) GetRName() []byte {
	if m != nil {
		return m.RName
	}
	return nil
}

func (m *StartOfAuthority) GetSerial() uint32 {
	if m != nil {
		return m.Serial
	}
	return 0
}

func (m *StartOfAuthority) GetRefresh() uint32 {
	if m != nil {
		return m.Refresh
	}
	return 0
}

func (m *StartOfAuthority) GetRetry() uint32 {
	if m != nil {
		return m.Retry
	}
	return 0
}

func (m *StartOfAuthority) GetExpire() uint32 {
	if m != nil {
		return m.Expire
	}
	return 0
}

func (m *StartOfAuthority) GetMinimum() uint32 {
	if m != nil {
		return m.Minimum
	}
	return 0
}

type MailExchange struct {
	Name                 []byte   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Preference           uint32   `protobuf:"varint,2,opt,name=preference,proto3" json:"preference,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MailExchange) Reset()         { *m = MailExchange{} }
func (m *MailExchange) String() string { return proto.CompactTextString(m) }
func (*MailExchange) ProtoMessage()    {}
func (*MailExchange) Descriptor() ([]byte, []int) {
	return fileDescriptor_638ff8d8aaf3d8ae, []int{8}
}

func (m *MailExchange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MailExchange.Unmarshal(m, b)
}
func (m *MailExchange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MailExchange.Marshal(b, m, deterministic)
}
func (m *MailExchange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MailExchange.Merge(m, src)
}
func (m *MailExchange) XXX_Size() int {
	return xxx_messageInfo_MailExchange.Size(m)
}
func (m *MailExchange) XXX_DiscardUnknown() {
	xxx_messageInfo_MailExchange.DiscardUnknown(m)
}

var xxx_messageInfo_MailExchange proto.InternalMessageInfo

func (m *MailExchange) GetName() []byte {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *MailExchange) GetPreference() uint32 {
	if m != nil {
		return m.Preference
	}
	return 0
}

type ServiceRecord struct {
	Name                 []byte   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Priority             uint32   `protobuf:"varint,2,opt,name=priority,proto3" json:"priority,omitempty"`
	Weight               uint32   `protobuf:"varint,3,opt,name=weight,proto3" json:"weight,omitempty"`
	Port                 uint32   `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceRecord) Reset()         { *m = ServiceRecord{} }
func (m *ServiceRecord) String() string { return proto.CompactTextString(m) }
func (*ServiceRecord) ProtoMessage()    {}
func (*ServiceRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_638ff8d8aaf3d8ae, []int{9}
}

func (m *ServiceRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceRecord.Unmarshal(m, b)
}
func (m *ServiceRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceRecord.Marshal(b, m, deterministic)
}
func (m *ServiceRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceRecord.Merge(m, src)
}
func (m *ServiceRecord) XXX_Size() int {
	return xxx_messageInfo_ServiceRecord.Size(m)
}
func (m *ServiceRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceRecord.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceRecord proto.InternalMessageInfo

func (m *ServiceRecord) GetName() []byte {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *ServiceRecord) GetPriority() uint32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func (m *ServiceRecord) GetWeight() uint32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *ServiceRecord) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func init() {
	proto.RegisterType((*DnsHeaderFlags)(nil), "main.DnsHeaderFlags")
	proto.RegisterType((*DnsHeader)(nil), "main.DnsHeader")
	proto.RegisterType((*Question)(nil), "main.Question")
	proto.RegisterType((*ResourceRecord)(nil), "main.ResourceRecord")
	proto.RegisterType((*DnsInfo)(nil), "main.DnsInfo")
	proto.RegisterType((*DnsPacket)(nil), "main.DnsPacket")
	proto.RegisterType((*DnsPacketBundle)(nil), "main.DnsPacketBundle")
	proto.RegisterType((*StartOfAuthority)(nil), "main.StartOfAuthority")
	proto.RegisterType((*MailExchange)(nil), "main.MailExchange")
	proto.RegisterType((*ServiceRecord)(nil), "main.ServiceRecord")
}

func init() { proto.RegisterFile("dns.proto", fileDescriptor_638ff8d8aaf3d8ae) }

var fileDescriptor_638ff8d8aaf3d8ae = []byte{
	// 895 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0xdb, 0x72, 0xdb, 0x36,
	0x10, 0x1d, 0x49, 0xd6, 0x85, 0x4b, 0x4b, 0x76, 0x60, 0x27, 0x65, 0xd3, 0x9b, 0xcb, 0x4e, 0x26,
	0x4a, 0x2f, 0xee, 0x54, 0x9d, 0xe9, 0x53, 0x5f, 0xec, 0xb8, 0x9d, 0xe8, 0xa1, 0x37, 0x34, 0xef,
	0x1c, 0x98, 0x58, 0x59, 0x98, 0x88, 0x20, 0x0b, 0x80, 0x8e, 0x9c, 0xa7, 0xfe, 0x43, 0xff, 0xa6,
	0x5f, 0xd1, 0x2f, 0xe8, 0xb7, 0x74, 0xb0, 0x20, 0x29, 0xdb, 0x93, 0xf6, 0xa5, 0x6f, 0xd8, 0xb3,
	0x87, 0xab, 0xc5, 0xd9, 0xb3, 0x10, 0x44, 0x52, 0xdb, 0xd3, 0xca, 0x94, 0xae, 0x64, 0x7b, 0x85,
	0x50, 0x3a, 0xfd, 0xbb, 0x07, 0xb3, 0x0b, 0x6d, 0x5f, 0xa0, 0x90, 0x68, 0xbe, 0xdf, 0x88, 0x2b,
	0xcb, 0xbe, 0x82, 0x63, 0x51, 0xbb, 0x75, 0x69, 0x94, 0x13, 0x4e, 0x5d, 0x63, 0x26, 0xb4, 0x7d,
	0x8d, 0x26, 0xe9, 0x9d, 0xf4, 0xe6, 0x13, 0x7e, 0x74, 0x27, 0x77, 0x46, 0x29, 0xf6, 0x05, 0x30,
	0x67, 0x6a, 0x9d, 0x0b, 0x87, 0x32, 0x33, 0x68, 0xab, 0x52, 0x5b, 0x4c, 0xfa, 0xf4, 0xc1, 0x83,
	0x2e, 0xc3, 0x9b, 0x04, 0xfb, 0x0c, 0x1e, 0x18, 0xcc, 0x6b, 0x63, 0x55, 0xa9, 0x33, 0x89, 0x56,
	0x19, 0x94, 0xc9, 0x80, 0xd8, 0x87, 0x5d, 0xe2, 0x22, 0xe0, 0xec, 0x4b, 0x38, 0xda, 0x91, 0xc5,
	0xb5, 0x50, 0x1b, 0x71, 0xb9, 0xc1, 0x64, 0x8f, 0xe8, 0xac, 0x4b, 0x9d, 0xb5, 0x19, 0xb6, 0x0f,
	0xbd, 0x37, 0xc9, 0xf0, 0xa4, 0x37, 0x9f, 0xf2, 0xde, 0x9b, 0xf4, 0xaf, 0x3e, 0x44, 0xdd, 0x05,
	0xd9, 0x63, 0x52, 0x20, 0x73, 0xdb, 0x4c, 0x49, 0xba, 0xd0, 0x94, 0x8f, 0xa5, 0xb6, 0x2f, 0xb7,
	0x4b, 0xc9, 0x3e, 0x82, 0x58, 0xd9, 0xfb, 0xdd, 0x83, 0xb2, 0x5d, 0xdb, 0xef, 0xc0, 0xb8, 0xac,
	0xb2, 0xbc, 0x94, 0x48, 0xcd, 0x4e, 0xf9, 0xa8, 0xac, 0x9e, 0x97, 0x12, 0xd9, 0xa7, 0x30, 0x5c,
	0x79, 0xe9, 0xa8, 0xa9, 0x78, 0x71, 0x7c, 0xea, 0xa5, 0x3d, 0xbd, 0x2b, 0x2b, 0x0f, 0x14, 0xf6,
	0x09, 0x4c, 0xdb, 0x9f, 0x08, 0xa5, 0x42, 0xa7, 0xfb, 0x2d, 0x48, 0x05, 0x9f, 0xc0, 0xec, 0xb7,
	0x1a, 0xad, 0xf3, 0x57, 0xce, 0xcb, 0x5a, 0xbb, 0x64, 0x44, 0xac, 0x69, 0x8b, 0x3e, 0xf7, 0x20,
	0xfb, 0x18, 0xf6, 0xc3, 0x6c, 0x1a, 0xd2, 0x98, 0x48, 0x71, 0xc0, 0x02, 0xe5, 0x29, 0x1c, 0xb4,
	0x03, 0xbb, 0x69, 0x58, 0x13, 0x62, 0xcd, 0x3a, 0x38, 0x10, 0x9f, 0xc1, 0xa1, 0x90, 0x52, 0xf9,
	0xe2, 0x62, 0xd3, 0x30, 0x23, 0x62, 0x1e, 0xec, 0x70, 0xa2, 0xa6, 0x2f, 0x60, 0xf2, 0x4b, 0xd3,
	0x07, 0x63, 0xb0, 0xa7, 0x45, 0x81, 0xa4, 0xe5, 0x3e, 0xa7, 0xb3, 0xc7, 0xdc, 0x4d, 0x15, 0x14,
	0x8c, 0x38, 0x9d, 0xd9, 0x31, 0x0c, 0xf3, 0x8d, 0xb0, 0x96, 0x94, 0x8b, 0x78, 0x08, 0xd2, 0x3f,
	0xfa, 0x30, 0xe3, 0x68, 0xcb, 0xda, 0xe4, 0xc8, 0x31, 0x2f, 0x8d, 0xfc, 0x7f, 0x05, 0xd9, 0x21,
	0x0c, 0x9c, 0xdb, 0xd0, 0x1c, 0xa6, 0xdc, 0x1f, 0xfd, 0x54, 0xad, 0x33, 0x4a, 0x5f, 0x65, 0x52,
	0x38, 0x41, 0x6a, 0x47, 0x1c, 0x02, 0x74, 0x21, 0x9c, 0x60, 0xef, 0x41, 0x74, 0x79, 0xe3, 0x30,
	0xa4, 0x47, 0xf4, 0xab, 0x13, 0x0f, 0x50, 0x72, 0x0e, 0x03, 0x5b, 0x0a, 0x12, 0x36, 0x5e, 0x3c,
	0x0a, 0x73, 0xfd, 0xd5, 0x09, 0xe3, 0x7e, 0x5a, 0x9d, 0xb5, 0xfa, 0x71, 0x4f, 0x61, 0x29, 0xf4,
	0x8b, 0x2d, 0x69, 0x1b, 0x2f, 0x58, 0x20, 0xfe, 0x20, 0xd4, 0xe6, 0xbb, 0x6d, 0xbe, 0x16, 0xfa,
	0x0a, 0x79, 0xbf, 0xd8, 0xb2, 0x27, 0x30, 0xb0, 0xe6, 0x9a, 0x64, 0x8d, 0x17, 0x47, 0x4d, 0x35,
	0x34, 0xd7, 0xaa, 0xbd, 0x3d, 0xf7, 0xf9, 0xf4, 0xf7, 0x3e, 0x8c, 0x2f, 0xb4, 0x5d, 0xea, 0x55,
	0xc9, 0x9e, 0xc2, 0x68, 0x4d, 0x26, 0x22, 0x41, 0xe2, 0xc5, 0xc1, 0x3d, 0x6f, 0xf1, 0x26, 0xcd,
	0x3e, 0x87, 0xa8, 0x35, 0x87, 0x4d, 0xfa, 0x27, 0x83, 0x79, 0xbc, 0x98, 0x05, 0x6e, 0x3b, 0x2b,
	0xbe, 0x23, 0xb0, 0x53, 0x18, 0x07, 0x97, 0x78, 0xfd, 0x06, 0x3b, 0xcf, 0xde, 0x1d, 0x06, 0x6f,
	0x49, 0xec, 0x1b, 0x88, 0x5b, 0xbf, 0x28, 0xf4, 0x3e, 0xff, 0xf7, 0x6f, 0x6e, 0x13, 0xe9, 0xbb,
	0xce, 0x3d, 0x36, 0x19, 0xfe, 0xe7, 0x77, 0x3b, 0xa2, 0x7f, 0x96, 0xfc, 0xd6, 0xfe, 0x2c, 0xf2,
	0x57, 0xe8, 0xd8, 0xfb, 0x10, 0x39, 0x55, 0xa0, 0x75, 0xa2, 0xa8, 0x48, 0x87, 0x01, 0xdf, 0x01,
	0xec, 0x03, 0x00, 0x65, 0x33, 0xa5, 0x2f, 0xcb, 0x5a, 0xcb, 0x66, 0x6d, 0x23, 0x65, 0x97, 0x01,
	0x60, 0xef, 0xc2, 0x04, 0xdd, 0x3a, 0x23, 0x03, 0x85, 0xb5, 0x1d, 0xa3, 0x5b, 0xbf, 0xf4, 0x1e,
	0x7a, 0x08, 0x23, 0x6b, 0xf2, 0x4c, 0x55, 0x64, 0x98, 0x88, 0x0f, 0xad, 0xc9, 0x97, 0x95, 0x87,
	0xa5, 0x75, 0x1e, 0x0e, 0x6e, 0x19, 0x4a, 0xeb, 0x96, 0x95, 0xdf, 0xb6, 0x8a, 0xfa, 0xc9, 0xbc,
	0x3d, 0x6c, 0xb3, 0x92, 0x71, 0xc0, 0xce, 0x3d, 0xc4, 0xe6, 0x30, 0xf1, 0xcf, 0x8b, 0xd2, 0xab,
	0xb2, 0xf1, 0xcc, 0xb4, 0x9b, 0x97, 0x1f, 0x27, 0x3d, 0x36, 0xfe, 0x90, 0x7e, 0x0b, 0x07, 0xdd,
	0xfd, 0xce, 0x6b, 0x2d, 0x37, 0xc8, 0x9e, 0xc1, 0x38, 0xd4, 0xb2, 0x49, 0x8f, 0x74, 0xda, 0xcd,
	0x3a, 0xf0, 0x78, 0x9b, 0x4f, 0xff, 0xec, 0xc1, 0xe1, 0x7d, 0x1b, 0xfa, 0xb6, 0x8b, 0xec, 0xd6,
	0xee, 0x0c, 0x8b, 0x1f, 0xfd, 0xf2, 0x3c, 0x84, 0x91, 0x09, 0x70, 0x3f, 0xc0, 0x86, 0xe0, 0x47,
	0x30, 0xb2, 0x68, 0x94, 0xd8, 0xb4, 0x6f, 0x59, 0x88, 0x58, 0x02, 0x63, 0x83, 0x2b, 0x83, 0x76,
	0xdd, 0x6c, 0x51, 0x1b, 0xfa, 0x8d, 0x33, 0xe8, 0xcc, 0x4d, 0xf3, 0x62, 0x85, 0xc0, 0xd7, 0xc1,
	0x6d, 0xa5, 0x0c, 0x36, 0x7a, 0x34, 0x91, 0xaf, 0x53, 0x28, 0xad, 0x8a, 0xba, 0x68, 0x9e, 0xa5,
	0x36, 0x4c, 0xcf, 0x61, 0xff, 0xf6, 0x66, 0xbc, 0x75, 0xe3, 0x3f, 0x04, 0xa8, 0x0c, 0xae, 0xd0,
	0xa0, 0xce, 0x43, 0xe3, 0x53, 0x7e, 0x0b, 0x49, 0x5f, 0xc1, 0xf4, 0xce, 0xe2, 0xbc, 0xb5, 0xc8,
	0x63, 0x98, 0x54, 0x46, 0x91, 0x38, 0x4d, 0x89, 0x2e, 0xf6, 0x6d, 0xbf, 0x46, 0x75, 0xb5, 0x76,
	0xed, 0xf5, 0x43, 0xe4, 0xeb, 0x54, 0xa5, 0x71, 0xcd, 0xdd, 0xe9, 0x7c, 0x39, 0xa2, 0x3f, 0xcc,
	0xaf, 0xff, 0x09, 0x00, 0x00, 0xff, 0xff, 0x6d, 0x70, 0x53, 0xaf, 0x3d, 0x07, 0x00, 0x00,
}
